### ISSUE TITLE
how to translator the origin?

### ISSUE THREAD

**Issue by leyap** [spark3dp/print-manager#12]
Hi,
Recently, we have successfully generated the gcode file in the local test.But this file couldn't operated in our own 3D printers because of the problem about the origin. Although we have read README in translator document and done related config work according to README, this problem couldn't resolved.
We also tried to adjust the bed_offset, but this didn't work and there weren't any changes in gcode. 
In addition, the gcode file which can run in our printers has negative coordinates(such as: G1 X-16.61 Y-4.57 E4.75417).So how to resolve this problem?

**Comment by masterhou** [comment]
please have a look of https://github.com/spark3dp/print-manager/blob/sandbox/spark-print-mgr/printableTranslation/FDMTranslatorDelta.js
