### ISSUE TITLE
does not build on node >= v0.11.x

### ISSUE THREAD

**Issue by morriswinkler** [spark3dp/print-manager#21]
please update package.json 

and change

-"usb-detection": "1.0.3",
+"usb-detection": "1.3.0",

otherwise it fails to build on a recent version of node.js

**Comment by ghost** [comment]
I'm in the process of testing and updating to 0.11.16 for windows and mac.

I'll also update usb to 1.1.1 whilst I'm there.

I'll close this issue when the updates are in,

**Comment by ghost** [comment]
updated
