### ISSUE TITLE
reference to closed bug #19, problem with adding new printer

### ISSUE THREAD

**Issue by morriswinkler** [spark3dp/print-manager#23]
Dear print manager team,

i am having similar issues, it is somewhat frustrating to get started with adding a new printer configuration. I can understand that you are still laying out things and the format is likely(hopefully) to change to a more convinient one ( no i am not trying to troll you, just for the users sake :)

Since issue #19 was resolved by talking back to the Autodesk support, i could just do the same. But the poor guys at the helpdesk would certainly be more happy if you could just provide a little write up on how to add a printer, maybe in the Readme under the data folder, or in the wiki , or just add it to this bug report so people can find it. I for one would sincerely bow down before you. 

Yours sincerely ( bowing down)

Morris Winkler

**Comment by ghost** [comment]
See  https://spark.autodesk.com/developers/reference/printer-manufacturers/integrate-your-printer/integrate-your-printer-model
