### ISSUE TITLE
Replicator 2X ?

### ISSUE THREAD

**Issue by tchapi** [spark3dp/print-manager#24]
Hi,
I see a dedicated branch for the Replicator 2X on this repo, but when I try to run this branch (Mac OS X 10.11) locally, either the Replicator 2X choice doesn't come up in Print Studio, or Print Manager refuses to start (with `sudo launchctl load –w /Library/LaunchDaemons/com.autodesk.printmanager.plist`).

How can I add locally this printer to my instance of Print Manager ? Am I missing something ? Will this be in the official release sometime soon ?

Thanks a lot

**Comment by ghost** [comment]
It is just there as an example on how to add a new printer. It is not functional.

There are no plans to add the 2X.

**Comment by tchapi** [comment]
Ok, fine. But then how do you add a new printer ? Following the R2X example does not work, and neither does the tutorial at https://spark.autodesk.com/developers/reference/printer-manufacturers/integrate-your-printer/integrate-your-printer-model

**Comment by ghost** [comment]
You follow the tutorial.

**Comment by tchapi** [comment]
... which lacks a lot of information and, when followed to the letter, doesn't work. But thanks for your very helpful answers !
