### ISSUE TITLE
How to set resolution of DLP printer?

### ISSUE THREAD

**Issue by jmkao** [spark3dp/print-manager#25]
I am in the process of integrating print-manager with my 3D printer, and have been able to follow the instructions and generate a build area with the correct physical dimensions and output PNG slices that are parseable by my printer.

However, my printer has a resolution of 1920x1080, and I am unable to find any place in code that controls the pixels dimensions of the output image, it seems to always generate a 1280x800 image.

Is there a location or configuration where I can set the pixel resolution that I'm missing?

**Comment by ghost** [comment]
No its our mistake. You need to edit a file in the Print Studio distribution.

You will find a file called emberConfig,json where PrintStudio is installed
C:\Program Files\Autodesk\Autodesk Print Studio\Resources

Edit these values and remove the “inUse” false flag and you should be able to change the size
    {
        "name": "img_width",
        "user_name": "Image width",
        "description": "Width of the projector image.",
        "type": "int",
        "default": 1280,
        "category": "Images",
        "in_use": false
    },

```
{
    "name": "img_height",
    "user_name": "Image height",
    "description": "Height of the projector image.",
    "type": "int",
    "default": 800,
    "category": "Images",
    "in_use": false
},
```
