### ISSUE TITLE
Problem on Mac Quick Start

### ISSUE THREAD

**Issue by nikoagge** [spark3dp/print-manager#27]
I try to make this code work on Mac but I have some problems. 

1) You say to add localConfig.json to spark-print-mgr directory, there is already config.json in spark-print-mgr directory, should I modify this or make a new one localConfig.json file?

2) Also I would like to know which npm version is suitable with Node 0.11.16 version?

**Comment by ghost** [comment]
You need to add a new file called localConfig.json with the path to the prep server that is contained in the release.

It happens to be npm 2.3.0. The best thing to use is https://www.npmjs.com/package/n this allows you to always have your version of node and npm in sync. It also is a easy way to switch versions.
