### ISSUE TITLE
How to include print manager code into local app

### ISSUE THREAD

**Issue by aksingh108** [spark3dp/print-manager#29]
Hi, 
I want to learn how can i integrate pint-manager-sandbox code given at "https://github.com/spark3dp/print-manager" into the webapp-samples code given at location "https://github.com/spark3dp/webapp-samples"  or into any local app so that files can be uploaded and printed using the print manager?
I want to know step wise like where to copy print-manager-code into web-samples-code folder. What changes needs to be done and how to run it finally for local 3d print discovery and sending print job to selected printer. 
Please guide.

Thanks 
Aks.

**Comment by ghost** [comment]
Print Manager is solely a desktop solution for managing printers. There is no connection to the webapp-samples

**Comment by aksingh108** [comment]
Hi mleedavies,

I understand it now. I am able to launch print manager at http://localhost:9998/console. 
I want to know how can i use this print-manager code to upload a file and send it to print to the selected printer. My intention is to extend the functionality? How can i add files which will have upload functionality and print functionality?

Thanks a lot in advance.
