### ISSUE TITLE
error: uncaughtException: EPERM, operation not permitted 

### ISSUE THREAD

**Issue by aksingh108** [spark3dp/print-manager#30]
Hi,

After 'npm instal'l when I run 'noder server.js' command on my windows 10 machine I get below mentioned error. 
error: uncaughtException: EPERM, operation not permitted 'C:\Users\Administrator\AppData\Roaming\Autodesk\PrintManager\files\766657e8-42cc-4a62-9e20-622b47ceb2b9.png
Could anybody please let me know how to resolve this issue?

Thanks,
Aks.

**Comment by ghost** [comment]
you need to run it as an administrator

**Comment by aksingh108** [comment]
Thanks. I was able to resolve this issue today. Thanks again for the help.
