### ISSUE TITLE
Extending print-manager functionality 

### ISSUE THREAD

**Issue by aksingh108** [spark3dp/print-manager#31]
Hi mleedavies,

I am able to launch print manager at http://localhost:9998/console without using print studio. 
I want to know how can i use this print-manager code to upload a file and send it to print to the selected printer. My intention is to create a desktop app which extends the functionality of existing print-manager? How can i add files which will have upload functionality and print functionality?

Thanks a lot in advance.

**Comment by ghost** [comment]
this should get you started .. its python.

import sys
import os
import requests
import json
from time import sleep
from urlparse import urlparse
from os.path import splitext, basename

baseURL = 'http://localhost:9998'

def waitForTask(response):

```
try:
    response.raise_for_status()
except e:
    return None

taskId = response.json()["id"]

url = baseURL + "/print/tasks/" + taskId

maxIterations = 100

while True:

    response = requests.get(url)

    json = response.json()

        #print "Progress = %f" % json["progress"]

    if json["progress"] == 1:
                    if json["status"] == "error":
                            print("errors", json["error"])
                        return None
        if "result" in json:
                            print("result", json["result"])
                            return json["result"]
        else:
            return None

    #maxIterations -= 1
    if maxIterations == 0:
        return None

    sleep(0.1)
```

def uploadToSparkDrive(fileName):

```
url = baseURL + "/files/upload"

files = {'file': open(fileName, 'rb')}

response = requests.post(url, files=files)

json = response.json()

return json["files"][0]["file_id"]
```

def importMesh(fileId, name):
    url = baseURL + "/geom/meshes/import"

```
payLoad = {"file_id": fileId, "name":name, "transform": [[1,0,0,0],[0,1,0,0],[0,0,1,0]]}

response = requests.post(url, json=payLoad)

    res = waitForTask(response)

    if (res):
         return res["id"]
    else:
         return 0
```

def renameMesh(meshId):
        url = baseURL + "/geom/meshes/rename"

```
payLoad = {"id": meshId, "name": "newName"}

response = requests.post(url, json=payLoad)

    print("response rename", response)

    json = response.json()

    print("json", json)

    if (json):
         return json["id"]
    else:
         return 0
```

def analyseMesh(meshId):
    url = baseURL + "/geom/meshes/analyze"

```
    payLoad = {"id": meshId}

    response = requests.post(url, json=payLoad)

    print("response anal", response)

    if (response.status_code == 202):
        res = waitForTask(response)
        if (res):
           return res["id"]
        else:
           return 0
    elif (response.status_code == 200):
        return meshId
    else:
        return 0
```

def main():

```
fileName = sys.argv[1]

fileId = uploadToSparkDrive(fileName)
print "Uploaded file to Spark Drive and got FileId",
print fileId


meshId = importMesh(str(fileId), "Input mesh")
if (meshId):
     print "Imported into Mesh engine and got meshId",
     print meshId
else:
     print "Import Mesh failed"
     exit()

meshId2 = analyseMesh(meshId)
if (meshId2):
     print "Mesh Analysis Succeeed",
 print meshId2
else:
     print "Mesh Analysis Failed"
     exit()

meshId3 = analyseMesh(meshId2)
if (meshId3): 
     print "Mesh Analysis Succeeed",
     print meshId3
else:
     print "Mesh Analysis Failed"
 exit()

meshId4 = renameMesh(meshId3)
if (meshId4):
     print "Rename Mesh Succedded",
 print meshId4
else:
     print "Mesh Rename Failed"
 exit()
```

if **name** == "**main**":
    main()

**Comment by aksingh108** [comment]
Hi Lee

Thanks a lot for help.  Just wanted to check where to create this file in print manager code downloaded from github and how to handle and run this.  I am able to install and run node server. Js and able to browse localhost:9998tel:9998/console.  It shows printer status page. This has links to edit and add printers.
I thought I can create some html files into the Base code which will upload local file and send to print.
Why is this python file required? How to achieve print functionality means send browse file to the printer to print? How to submit this job to printer which will start printing?

Plz write in detail as I am new to this technology.

Thanks.
aks.

Sent from my Mi phone
On mleedavies notifications@github.com, 13 Jun 2016 10:05 pm wrote:

this should get you started .. its python.

import sys
import os
import requests
import json
from time import sleep
from urlparse import urlparse
from os.path import splitext, basename

baseURL = 'http://localhost:9998'

def waitForTask(response):

try:
    response.raise_for_status()
except e:
    return None

taskId = response.json()["id"]

url = baseURL + "/print/tasks/" + taskId

maxIterations = 100

while True:

```
response = requests.get(url)

json = response.json()

    #print "Progress = %f" % json["progress"]

if json["progress"] == 1:
                if json["status"] == "error":
                        print("errors", json["error"])
                    return None
    if "result" in json:
                        print("result", json["result"])
                        return json["result"]
    else:
        return None

#maxIterations -= 1
if maxIterations == 0:
    return None

sleep(0.1)
```

def uploadToSparkDrive(fileName):

url = baseURL + "/files/upload"

files = {'file': open(fileName, 'rb')}

response = requests.post(url, files=files)

json = response.json()

return json["files"][0]["file_id"]

def importMesh(fileId, name):
url = baseURL + "/geom/meshes/import"

payLoad = {"file_id": fileId, "name":name, "transform": [[1,0,0,0],[0,1,0,0],[0,0,1,0]]}

response = requests.post(url, json=payLoad)

```
res = waitForTask(response)

if (res):
     return res["id"]
else:
     return 0
```

def renameMesh(meshId):
url = baseURL + "/geom/meshes/rename"

payLoad = {"id": meshId, "name": "newName"}

response = requests.post(url, json=payLoad)

```
print("response rename", response)

json = response.json()

print("json", json)

if (json):
     return json["id"]
else:
     return 0
```

def analyseMesh(meshId):
url = baseURL + "/geom/meshes/analyze"

```
payLoad = {"id": meshId}

response = requests.post(url, json=payLoad)

print("response anal", response)

if (response.status_code == 202):
    res = waitForTask(response)
    if (res):
       return res["id"]
    else:
       return 0
elif (response.status_code == 200):
    return meshId
else:
    return 0
```

def main():

fileName = sys.argv[1]

fileId = uploadToSparkDrive(fileName)
print "Uploaded file to Spark Drive and got FileId",
print fileId

meshId = importMesh(str(fileId), "Input mesh")
if (meshId):
     print "Imported into Mesh engine and got meshId",
     print meshId
else:
     print "Import Mesh failed"
     exit()

meshId2 = analyseMesh(meshId)
if (meshId2):
     print "Mesh Analysis Succeeed",
 print meshId2
else:
     print "Mesh Analysis Failed"
     exit()

meshId3 = analyseMesh(meshId2)
if (meshId3):
     print "Mesh Analysis Succeeed",
     print meshId3
else:
     print "Mesh Analysis Failed"
 exit()

meshId4 = renameMesh(meshId3)
if (meshId4):
     print "Rename Mesh Succedded",
 print meshId4
else:
     print "Mesh Rename Failed"
 exit()

if name == "main":
main()

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/spark3dp/print-manager/issues/31#issuecomment-225636336, or mute the threadhttps://github.com/notifications/unsubscribe/ANiihHFtFDUTnxiJthZjcku1QXosPBdWks5qLYbTgaJpZM4Iy8r8.

---

## DISCLAIMER: This electronic message and any attachments to this electronic message is intended for the exclusive use of the addressee(s) named herein and may contain legally privileged and confidential information. It is the property of Celstream Technologies Private Limited. If you are not the intended recipient, you are hereby strictly notified not to copy, forward, distribute or use this message or any attachments thereto. If you have received this message in error, please delete it and all copies thereof, from your system and notify the sender at Celstream Technologies or administrator@celstream.com immediately.

**Comment by ghost** [comment]
The python file is there simply to provide an example on how to call the API's which is what I thought "How can i add files which will have upload functionality and print functionality?" meant. If you want to have a html page to load a file to this system you will need to write that. I'm not sure if you just need to use print studio?

**Comment by aksingh108** [comment]
Hi
I don't want to use print studio.. Just want to use print manager which runs on my machine after following the steps npm install and node server. js.
I will write html file which will have browse button... Java script code will provide the functionality...
Then I will add printer using the print manager Web page and send the browsed file to the printer to print.
I just wanted to to achieve this.
Please guide if I am right or wrong and how to submit a job to the printer.
Please let me know the api to print job to selected printer and how to use it.

Thanks a lot in advance.

Sent from my Mi phone
On mleedavies notifications@github.com, 13 Jun 2016 10:32 pm wrote:

The python file is there simply to provide an example on how to call the API's which is what I thought "How can i add files which will have upload functionality and print functionality?" meant. If you want to have a html page to load a file to this system you will need to write that. I'm not sure if you just need to use print studio?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHubhttps://github.com/spark3dp/print-manager/issues/31#issuecomment-225643909, or mute the threadhttps://github.com/notifications/unsubscribe/ANiihKXm1NF3BAHf_-aGK5cl-flfGfnMks5qLY0kgaJpZM4Iy8r8.

---

## DISCLAIMER: This electronic message and any attachments to this electronic message is intended for the exclusive use of the addressee(s) named herein and may contain legally privileged and confidential information. It is the property of Celstream Technologies Private Limited. If you are not the intended recipient, you are hereby strictly notified not to copy, forward, distribute or use this message or any attachments thereto. If you have received this message in error, please delete it and all copies thereof, from your system and notify the sender at Celstream Technologies or administrator@celstream.com immediately.

**Comment by aksingh108** [comment]
Hi Lee,

I just wanted to clarify my requirement. When i launch print-manager without print studio after "npm install" and "node server.js", I am able to browse localhost:9998/console. If we navigate with buttons on this page we get staus, Edit Printer, Add Printer pages. 
I want to create file upload file which will upload g-code file from local system and select one of the added 3d printer and send this file to the printer to print. I want to achieve this using html and javascript file only.
I just wanted to know how can i achieve this in the print-manager-code downloaded from github?
Could you please guide me the api's or functions to be used for upload and send to print using javascript and html?
Also what are local spark api's for upload and print and their input parameters?

Thanks & regards,
Aks.
